name: samsun_transit
description: Samsun Transit Serverless Native App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0          # db_service.dart için zorunlu
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/samsun_mobil.db
    - assets/logo.png
    - assets/samulas.png
    - assets/odak.png
    - assets/samair.png
    - assets/bus.png
    - assets/bus_stop.png
